POST http://localhost:5000/transaction
Content-Type: application/json

{
    "payer": "self",
    "payee": "rawal",
    "amount": 50,
    "description": "roomrent",
    "date": "25-05-2020",
    "time": "12:30"
}

###

GET http://localhost:5000/transaction

###

GET http://localhost:5000/transaction/1

###

PATCH http://localhost:5000/transaction/5
Content-Type: application/json

{
    "payer": "self",
    "payee": "rawal",
    "amount": 750,
    "description": "room-rent",
    "date": "04-25-2020",
    "time": "05:30"
}

###

DELETE http://localhost:5000/transaction/2